// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC3WOV-Rxd7VcaMfU3KDAeSp_CxakJU0tI',
    appId: '1:561656185663:web:cb65e208f756cde4b7898a',
    messagingSenderId: '561656185663',
    projectId: 'udemy-firebase-dersi',
    authDomain: 'udemy-firebase-dersi.firebaseapp.com',
    storageBucket: 'udemy-firebase-dersi.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCBBep8ofhIzhC3CqkZAnTPxyHbXgKfy6Q',
    appId: '1:561656185663:android:b0782ee1231572cdb7898a',
    messagingSenderId: '561656185663',
    projectId: 'udemy-firebase-dersi',
    storageBucket: 'udemy-firebase-dersi.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCpBejKwEYkWMKa5Jp9saVa_2gBeiN2j4w',
    appId: '1:561656185663:ios:7dd7879e9c70cf79b7898a',
    messagingSenderId: '561656185663',
    projectId: 'udemy-firebase-dersi',
    storageBucket: 'udemy-firebase-dersi.appspot.com',
    iosClientId: '561656185663-f79sfei1me68splgi378hjfst4nf0bfm.apps.googleusercontent.com',
    iosBundleId: 'com.example.fireBaseDenemeleri1',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCpBejKwEYkWMKa5Jp9saVa_2gBeiN2j4w',
    appId: '1:561656185663:ios:7dd7879e9c70cf79b7898a',
    messagingSenderId: '561656185663',
    projectId: 'udemy-firebase-dersi',
    storageBucket: 'udemy-firebase-dersi.appspot.com',
    iosClientId: '561656185663-f79sfei1me68splgi378hjfst4nf0bfm.apps.googleusercontent.com',
    iosBundleId: 'com.example.fireBaseDenemeleri1',
  );
}
